name: Question for the Chictech-2024 workshop
description: Use this template if you have a question from the ChicTech-2024 exercises.
title: "DESCRIPTIVE SUMMARY OF WHAT'S GOING ON"
labels: ["help wanted"]
body:
  - type: input
    attributes:
      label: Exercise name
      description: What exercise are you on?
      placeholder: 
    validations:
      required: true
  - type: textarea
    attributes:
      label: Description of the problem
      description: What's going on? (Please be specific - "it's not working" is not specific. )
      placeholder: Enter a description of your problem here.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Your code
      description: Please paste your code here. 
      placeholder: For better legibility, please type "```" before and after your code so the code is formatted properly. 
    validations:
      required: true
  - type: textarea
    attributes:
      label: Errors
      description: Please paste the error you got. 
      placeholder: For better legibility, please use code blocks when pasting. 
    validations:
      required: true
  - type: textarea
    attributes:
      label: More details (optional)
      description: Add any additional details here. 
      placeholder: For better legibility, please use code blocks when pasting. 
    validations:
      required: false
      
